### PR TITLE
feat: apply small fixes

### LINKED ISSUE #346: Rename recycle to trash

### LINKED ISSUE #351: Copy and move in shared items
This should be handled in the graasp-ui component.

### LINKED ISSUE #385: Change Username to Pseudonyme

### PR DESCRIPTION
**Pull request by pyphilia**
This PR introduces small fixes:
- close #346 
- close #351 
- close #385 
- fix breadcrumb navigation
- show member in shared items table
- clear email input on invite

### CODE REVIEW

File: src/components/main/TreeModal.js [hunk 1]
```diff
@@ -24,26 +28,36 @@ const useStyles = makeStyles(() => ({
...
 
-const { useItem, useItems, useOwnItems, useChildren } = hooks;
+const { useItem, useItems, useOwnItems, useChildren, useSharedItems } = hooks;
 
 const TreeModal = ({ itemIds, open, title, onClose, onConfirm, prevent }) => {
   const { t } = useTranslation();
   const classes = useStyles();
-  const { data: ownItems, isLoading } = useOwnItems();
+  const { data: ownItems, isLoading: isOwnItemsLoading } = useOwnItems();
+  // bug: get only shared items with write/admin rights
```
Comment (dialexo) [inline src/components/main/TreeModal.js:37]: I am not sure if the bug consists in `useSharedItems` only fetching shared items with write / admin rights (while it should in fact fetch all of them) or if it actually is the expected behaviour (and instead it fetches too many).

File: src/components/main/TreeModal.js [hunk 2]
```diff
@@ -24,26 +28,36 @@ const useStyles = makeStyles(() => ({
...
-  const buildExpandedItems = () => {
+  const buildExpandedItems = (rootId) => {
     if (items && !items.isEmpty()) {
       // suppose all items are in the same parent
       const parentIds = getParentsIdsFromPath(items.first().path) || [];
-      const newExpandedItems = [ROOT_ID, ...parentIds];
-      return newExpandedItems;
+      // return expanded list depending current root id
+      // define root depending on whether is the root parent is in the owned items
+      const rootItemId = parentIds[0];
```
Comment (dialexo) [inline src/components/main/TreeModal.js:49]: We access `parentIds` at index 0, but the line above specifies that the array may be empty if `getParentIdsFromPath` returns falsy.

File: src/components/main/TreeModal.js [hunk 3]
```diff
@@ -24,26 +28,36 @@ const useStyles = makeStyles(() => ({
...
+      const oItem = ownItems.find(({ id }) => id === rootItemId);
```
Comment (dialexo) [inline src/components/main/TreeModal.js:50]: Nitpick: convert to `Boolean()` and use a more explicit name, e.g. `isRootItemOwned` ?

File: src/components/main/TreeModal.js [hunk 4]
```diff
@@ -24,26 +28,36 @@ const useStyles = makeStyles(() => ({
...
+      const itemRootId = oItem ? ROOT_ID : SHARED_ROOT_ID;
```
Comment (dialexo) [inline src/components/main/TreeModal.js:51]: Info: what is `ROOT_ID`? The default ID of the member's root?

File: src/components/main/TreeModal.js [hunk 5]
```diff
@@ -24,26 +28,36 @@ const useStyles = makeStyles(() => ({
...
+      if (rootId === itemRootId) {
```
Comment (dialexo) [inline src/components/main/TreeModal.js:52]: What is this `rootId` then? Isn't it a roundabout way to check `rootId` against `ROOT_ID` or `SHARED_ROOT_ID`? If I understood correctly, depending on whether the root is the member's owned items or shared items, we should check if the first parent is either of these roots.

File: src/components/main/TreeModal.js [hunk 6]
```diff
@@ -24,26 +28,36 @@ const useStyles = makeStyles(() => ({
...
-  const { data: ownItems, isLoading } = useOwnItems();
+  const { data: ownItems, isLoading: isOwnItemsLoading } = useOwnItems();
+  // bug: get only shared items with write/admin rights
+  const { data: sharedItems, isLoading: isSharedItemsLoading } =
+    useSharedItems();
   const [selectedId, setSelectedId] = useState(null);
   const { data: items, isItemLoading } = useItems(itemIds);
 
-  const buildExpandedItems = () => {
+  const buildExpandedItems = (rootId) => {
```
Comment (dialexo) [inline src/components/main/TreeModal.js:43]: I'm not sure if I understand the function from reading it

File: src/components/main/TreeModal.js [hunk 7]
```diff
@@ -24,26 +28,36 @@ const useStyles = makeStyles(() => ({
...
+      const rootItemId = parentIds[0];
+      const oItem = ownItems.find(({ id }) => id === rootItemId);
+      const itemRootId = oItem ? ROOT_ID : SHARED_ROOT_ID;
+      if (rootId === itemRootId) {
+        const newExpandedItems = [rootId, ...parentIds];
+        return newExpandedItems;
+      }
     }
-    return [ROOT_ID];
+    return [];
```
Comment (dialexo) [inline src/components/main/TreeModal.js:57]: Info: why is the return value empty otherwise?

File: src/components/main/TreeModal.js [hunk 8]
```diff
@@ -82,24 +96,44 @@ const TreeModal = ({ itemIds, open, title, onClose, onConfirm, prevent }) => {
...
+        rootLabel={t('Owned Items')}
+        rootId={ROOT_ID}
+        rootClassName={buildTreeItemClass(ROOT_ID)}
+        showItemFilter={isFolder}
+        shouldFetchChildrenForItem={isFolder}
+        isTreeItemDisabled={isTreeItemDisabled}
+        buildTreeItemClass={buildTreeItemClass}
+      />
+      <DynamicTreeView
+        // id={TREE_MODAL_TREE_ID}
```
Comment (dialexo) [inline src/components/main/TreeModal.js:119]: Info: should we assign another ID for this second TreeView?

File: src/config/constants.js [hunk 9]
```diff
@@ -70,7 +70,9 @@ export const DEFAULT_IMAGE_SRC =
 // time to be considered between 2 clicks for a double-click (https://en.wikipedia.org/wiki/Double-click#Speed_and_timing)
 export const DOUBLE_CLICK_DELAY_MS = 500;
 
+// root used for tree item menu
 export const ROOT_ID = 'root-id';
+export const SHARED_ROOT_ID = 'shared-root-id';
```
Comment (dialexo) [inline src/config/constants.js:75]: style: are other IDs camelCase?

```suggestion
export const ROOT_ID = 'rootId';
export const SHARED_ROOT_ID = 'sharedRootId';
```

File: src/langs/en.json [hunk 10]
```diff
@@ -128,8 +127,8 @@
     "No user has access to this item.": "No user has access to this item.",
     "Authorized Members": "Authorized Members",
     "Authenticated Members": "Authenticated Members",
-    "Username and Password": "Username and Password",
-    "Username": "Username",
+    "Pseudonyme and Password": "Pseudonyme and Password",
+    "Pseudonyme": "Pseudonyme",
```
Comment (dialexo) [inline src/langs/en.json:131]:
```suggestion
    "Pseudonym and Password": "Pseudonym and Password",
    "Pseudonym": "Pseudonym",
```

File: src/langs/fr.json [hunk 11]
```diff
@@ -117,20 +116,20 @@
...
-    "Pseudonymized": "Avec pseudonyme",
+    "Pseudonymized": "Pseudomisé",
     "Sharing": "Partage",
     "No user has access to this item.": "Aucun utilisateur ne peut accéder à cet élément.",
     "Authorized Members": "Membres Autorisés",
     "Authenticated Members": "Membres Connectés",
-    "Username and Password": "Nom d'utilisateur et Mot de passe",
-    "Username": "Nom d'utilisateur",
+    "Pseudonyme and Password": "Pseudonyme et Mot de passe",
+    "Pseudonyme": "Pseudonyme",
```
Comment (dialexo) [inline src/langs/fr.json:132]:
```suggestion
    "Pseudonym and Password": "Pseudonyme et Mot de passe",
    "Pseudonym": "Pseudonyme",
```

**Review by dialexo — CHANGES_REQUESTED** [review]
Nice thanks! 🐶 I have a few nitpicks regarding style, translations, and some parts of the code I'm not sure I understand

File: src/components/main/TreeModal.js (hunk 1 above)
Comment (pyphilia) [reply src/components/main/TreeModal.js:37]: It is the intended behavior, but in this context it will result in a bug. I will change with `todo` it will be clearer indeed.
