### PR TITLE
fix: fix undefined items for creators, add file upload indications

### LINKED ISSUE #401: Rename Explorer to Library

### LINKED ISSUE #415: Editing a folder description and accessing "My Items" crashes the app
There's a bug in which editing the description of a folder and then navigating back to the top level "My Items" (whether through the breadcrumbs trail or the left menu) crashes the app:

https://user-images.githubusercontent.com/14943421/185576191-62189856-354c-4206-a437-f59d21a5bc3c.mp4

Console logs:

```logs
TypeError: can't convert undefined to object
    vo Items.js:36
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    o helpers.ts:95
instrument.ts:123
    v instrument.ts:123
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    o helpers.ts:95
```

```logs
Uncaught TypeError: can't convert undefined to object
    vo Items.js:36
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    o helpers.ts:95
Items.js:36:11
    vo Items.js:36
    React 6
    Os self-hosted:1198
    Qo React
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    bind_applyFunctionN self-hosted:1349
    Qt self-hosted:1312
    o helpers.ts:95
```

### LINKED ISSUE #417: Add warning for file upload
```
If you drag-and-drop zip or H5P archives, or if you any of them as a new “FILE", they will just be stored as such. To expend and use them, use the special “IMPORT ZIP” or “IMPORT H5P” option of the “+ NEW ITEM” dialog.
```

### LINKED ISSUE #420: bug: after setting an item's visibility to "pseudonymized", it cannot be set to private again
https://user-images.githubusercontent.com/14943421/186452709-c17c9e9c-d4a3-4052-ad40-8a5a1e2c08b3.mp4

### LINKED ISSUE #421: Long text enlarges the information menu
If the item has a very long name (without spaces) it breaks the layout of the information menu.
Breaking it might solve the problem.

Screenshot 2022-08-30 at 09 52 55

### LINKED ISSUE #422: Add uppy file size limit for zip and h5p
Uppy provides a parameter to prevent big files being submitted. This limit should be sync with the backend.

We should also trigger an error message for this.

### PR DESCRIPTION
**Pull request by pyphilia**
- close #401 
- fix #415 
- close #417 
- close #421 
- close #420
- close #422

### CODE REVIEW

File: src/components/file/FileDashboardUploader.js [hunk 1]
```diff
@@ -19,27 +21,26 @@ const FileDashboardUploader = () => {
   return (
     <>
       <Typography variant="h6">{t('Upload a File')}</Typography>
+      <Typography variant="body" paragraph>
+        {t(
+          'If you drag-and-drop zip or H5P archives, or if you any of them as a new “FILE", they will just be stored as such. To expend and use them, use the special “IMPORT ZIP” or “IMPORT H5P” option.',
```
Comment (dialexo) [inline src/components/file/FileDashboardUploader.js:26]:
```suggestion
          'If you drag-and-drop zip or H5P archives, or if you import them as a new “FILE", they will only be stored as such. To expand and use them, use the special “IMPORT ZIP” or “IMPORT H5P” option.',
```

File: src/components/main/ImportH5P.js [hunk 2]
```diff
@@ -63,33 +65,27 @@ const ImportH5P = () => {
...
+          maxSize: prettyBytes(MAX_ZIP_FILE_SIZE),
+        })}
+      </Typography>
       <div id={H5P_DASHBOARD_UPLOADER_ID}>
         <Dashboard
           uppy={uppy}
           height={200}
           width="100%"
           proudlyDisplayPoweredByUppy={false}
-          note={t('Upload a file')}
```
Comment (dialexo) [inline src/components/main/ImportH5P.js:83]: Do we remove the text hints?

File: src/langs/en.json [hunk 3]
```diff
@@ -61,7 +61,12 @@
     "Drop here or": "Drop here or",
     "Browse": "Browse",
     "Upload a file": "Upload a file",
-    "You can upload up to FILE_UPLOAD_MAX_FILES files at a time": "You can upload up to {{maxFiles}} files at a time",
+    "If you drag-and-drop zip or H5P archives, or if you upload any of them as a new \"FILE\", they will just be stored as such. To expend and use them, use the special \"IMPORT ZIP\" or \"IMPORT H5P\" option.": "If you drag-and-drop zip or H5P archives, or if you upload any of them as a new \"FILE\", they will just be stored as such. To expend and use them, use the special \"IMPORT ZIP\" or \"IMPORT H5P\" option.",
```
Comment (dialexo) [inline src/langs/en.json:64]:
```suggestion
    "If you drag-and-drop zip or H5P archives, or if you upload them as a new \"FILE\", they will only be stored as such. To expand and use them, use the special \"IMPORT ZIP\" or \"IMPORT H5P\" option.": "If you drag-and-drop zip or H5P archives, or if you upload any of them as a new \"FILE\", they will just be stored as such. To expend and use them, use the special \"IMPORT ZIP\" or \"IMPORT H5P\" option.",
```

**Review by dialexo — APPROVED** [review]
Just some minor textual changes, other LGTM ⚡

File: src/components/main/ImportH5P.js (hunk 2 above)
Comment (pyphilia) [reply src/components/main/ImportH5P.js:83]: I've removed them because I couldn't make them show. Anyway we need to upgrade the uppy dependencies so we can move them back later.
