### PR TITLE
155/blocked popup

### LINKED ISSUE #114: Improve Redirection Page Layout
Improve the content returned when the redirection function failed. It actually happens quite often since the browser blocks popup/redirection https://github.com/graasp/graasp-compose/issues/155
Currently the content is only a link.

### LINKED ISSUE #155: Automatic redirection is blocked
image

Resolving this issue might be a good solution as well https://github.com/graasp/graasp-compose/issues/114

### PR DESCRIPTION
**Pull request by pyphilia**
close #155 
close #114

### CODE REVIEW

File: src/components/layout/Header.js [hunk 1]
```diff
@@ -62,8 +64,8 @@ const Header = ({ isMenuOpen, toggleMenu }) => {
         <div className={classes.headerLeft}>
           {renderMenuIcon()}
           <Link to={HOME_PATH} className={classes.link}>
-            <GraaspLogo className={classes.logo} />
-            <Typography variant="h6" color="inherit">
+            <GraaspLogo height={40} className={classes.logo} />
```
Comment (juancarlosfarah) [inline src/components/layout/Header.js:67]: Factor the `40` out?

File: src/components/layout/Header.js [hunk 2]
```diff
@@ -24,8 +24,10 @@ const useStyles = makeStyles((theme) => ({
     alignItems: 'center',
   },
   logo: {
-    height: '40px',
-    margin: theme.spacing(0, 2),
+    fill: 'white',
+  },
+  title: {
+    margin: theme.spacing(0, 1.5),
```
Comment (juancarlosfarah) [inline src/components/layout/Header.js:30]: Not sure it's best practice to use decimals, as this then gets multiplied by a pixel number and could result in half pixels.

https://material-ui.com/customization/spacing/

**Review by juancarlosfarah — CHANGES_REQUESTED** [review]
Looks good! Just some minor comments and questions.
