### PR TITLE
148/bugs

### LINKED ISSUE #148: Editing an item in File View, then going to Own Items renders blank screen
```
react_devtools_backend.js:2560 TypeError: Cannot read property 'toLowerCase' of undefined
    at ItemSearch.js:110
    at immutable.es.js:1295
    at t.__iterate (immutable.es.js:3238)
    at t.Te.i.__iterateUncached (immutable.es.js:1294)
    at t.__iterate (immutable.es.js:320)
    at t.forEach (immutable.es.js:4753)
    at immutable.es.js:3074
    at t.xt [as withMutations] (immutable.es.js:2246)
    at t [as constructor] (immutable.es.js:3072)
    at ze (immutable.es.js:1793)
```

Steps:
- Create a link
- Go to Link
- Edit Caption and Save
- Go to Own Items through breadcrumbs navigation
- This (sometimes) displays a blank screen

### LINKED ISSUE #149: Empty Favorite Items returns Error screen and doesn't display return button/mainmenu

### PR DESCRIPTION
**Pull request by pyphilia**
close #148 
close #149

### CODE REVIEW

File: src/components/item/ItemContent.js [hunk 1]
```diff
@@ -137,6 +137,7 @@ const ItemContent = ({ item }) => {
             editCaption={isEditing}
             onSaveCaption={onSaveCaption}
             saveButtonId={saveButtonId}
+            height={500}
```
Comment (juancarlosfarah) [inline src/components/item/ItemContent.js:140]: Do we want to factor this out?

File: cypress/integration/item/favorite/favoriteItem.spec.js [hunk 2]
```diff
@@ -22,54 +23,89 @@ const toggleFavoriteButton = (itemId) => {
...
+
+      const itemId = favoriteItems[0];
+
+      cy.get(`#${buildItemsTableRowId(itemId)}`).should('exist');
+    });
   });
 
-  it('check favorite items view', () => {
-    cy.visit(FAVORITE_ITEMS_PATH);
+  describe('Errors handling', () => {
```
Comment (juancarlosfarah) [inline cypress/integration/item/favorite/favoriteItem.spec.js:79]: Minor Typo: `Error Handling`.

**Review by juancarlosfarah — CHANGES_REQUESTED** [review]
Thanks for the fixes! Just a quick comment and a question.
